version: "3"

services:
  auctiondb:
    image: mongo
    ports:
        - "27017:27017"
    container_name: auctiondb

  webserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - APP_ENV=DEV
      - DB_HOST_DEV=auctiondb
      - DB_PORT_DEV=27017
      - DB_NAME_DEV=auction
      - DB_CONNECTION_POOL_DEV=10
      - APP_SERVER_PORT_DEV=8000
      - APP_SECRET_DEV="SECRETS BE TOLS"

    ports:
      - "8000:8000"
    links:
      - "auctiondb:database"
    